version: '3.1'

services:

  mysql:
    image: mysql
    container_name: glue_service_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - "3307:3307"
  # redis:
  #   image: redis
  #   container_name: auth_service_redis
  #   ports: 
  #     - "6379:6379"