version: '3.1'

services:

  mysql:
    image: mysql
    platform: linux/amd64
    container_name: auth_service_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  redis:
    image: redis
    container_name: auth_service_redis
    ports: 
      - "6379:6379"